Description: >
    Eredjep Kadyrov VPC test 
    for Cloudformation
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true 